---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/auth/login":
    post:
      summary: create session
      tags:
      - Authentication
      description: Authenticates an user and returns a jwt token
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successfull_login:
                  value:
                    token: ASDFARasdfasdf13ADSFAGASD
                    user:
                      name: User
                      user_id: 1
        '401':
          description: Invalid params
          content:
            application/json:
              examples:
                invalid_credentials:
                  value:
                    error: Wrong email or password.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/tours":
    get:
      summary: get list of tours
      tags:
      - Tour
      description: List all tours
      security:
      - bearer_auth: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                successful:
                  value:
                  - id: 1
                    title: Tour Title
                    duration: '3.0'
                    city: City
                    description: Description
                    cost: '100.0'
                    photo: https://image.jpg
                    user_id: 1
                    created_at: '2022-09-21T15:41:25.060Z'
                    updated_at: '2022-09-21T15:41:25.060Z'
                  - id: 2
                    title: Tour Title
                    duration: '3.0'
                    city: City
                    description: Description
                    cost: '100.0'
                    photo: https://image.jpg
                    user_id: 2
                    created_at: '2022-09-21T15:41:25.060Z'
                    updated_at: '2022-09-21T15:41:25.060Z'
    post:
      summary: New tour
      tags:
      - Tour
      description: Create a new tour
      security:
      - bearer_auth: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Successful
          content:
            application/json:
              examples:
                successful:
                  value:
                    id: 1
                    title: Tour Title
                    duration: '3.0'
                    city: City
                    description: Description
                    cost: '100.0'
                    photo: https://image.jpg
                    user_id: 1
                    created_at: '2022-09-21T15:41:25.060Z'
                    updated_at: '2022-09-21T15:41:25.060Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                duration:
                  type: number
                city:
                  type: string
                description:
                  type: string
                cost:
                  type: number
                photo:
                  type: string
                user_id:
                  type: integer
              required:
              - title
              - duration
              - city
              - description
              - cost
              - photo
              - user_id
  "/tours/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete tours
      tags:
      - Tour
      description: Delete a tour
      security:
      - bearer_auth: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '204':
          description: successful
    get:
      summary: get specific tour
      tags:
      - Tour
      description: Get a tour
      security:
      - bearer_auth: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/users":
    post:
      summary: create new user
      tags:
      - Authentication
      description: Create a new user
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              examples:
                successfull_login:
                  value:
                    id: 1
                    name: user
                    created_at: '2022-09-23T16:35:16.614Z'
                    updated_at: '2022-09-23T16:35:16.614Z'
                    email: user@gmail.com
                    password_digest: "$2a$12$Dqn9G4HpoJQu3xh6GCEGKOr6vuZJf8afop4SLPaexOTjfG04vn8c6"
        '422':
          description: Invalid credentials
          content:
            application/json:
              examples:
                blank_name:
                  value:
                    errors:
                    - Name can't be blank
                blank_email:
                  value:
                    errors:
                    - Email can't be blank
                username_taken:
                  value:
                    errors:
                    - Password can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password
  "/user_tours":
    get:
      summary: Retrieves reservations
      tags:
      - Reservations
      description: Retrieves reservations for a user
      security:
      - bearer_auth: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                successful:
                  value:
                  - tour:
                      id: 1
                      title: First Tour
                      duration: '2.0'
                      city: Mansoura
                      description: In this tour we will visit x and ...
                      cost: '500.0'
                      photo: https://www.mans.edu.eg/images/album/mansoura-city/mc-nile.jpg
                      user_id: 1
                      created_at: '2022-09-22T00:27:45.651Z'
                      updated_at: '2022-09-22T00:27:45.651Z'
                    persons_number: 3
                    reservation_date: '2022-10-22'
                    reservation_id: 1
                  - tour:
                      id: 2
                      title: Second Tour
                      duration: '3.0'
                      city: Sharm El Sheikh
                      description: In this tour we will visit y and ...
                      cost: '600.0'
                      photo: https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/33/fc/ed/sharm-el-sheikh.jpg?w=700&h=500&s=1
                      user_id: 2
                      created_at: '2022-09-22T00:27:45.670Z'
                      updated_at: '2022-09-22T00:27:45.670Z'
                    persons_number: 2
                    reservation_date: '2022-10-22'
                    reservation_id: 2
    post:
      summary: New reservation
      tags:
      - Reservations
      description: Create a new reservation
      security:
      - bearer_auth: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Successful
          content:
            application/json:
              examples:
                successful:
                  value:
                    id: 1
                    reservation_date: '2022-10-21'
                    persons_number: 2
                    user_id: 1
                    tour_id: 1
                    created_at: '2022-09-21T15:41:25.060Z'
                    updated_at: '2022-09-21T15:41:25.060Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                persons_number:
                  type: integer
                reservation_date:
                  type: string
                user_id:
                  type: integer
                tour_id:
                  type: integer
              required:
              - persons_number
              - tour_id
              - user_id
  "/user_tours/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete reservation
      tags:
      - Reservations
      description: Delete a reservation
      security:
      - bearer_auth: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '204':
          description: successful
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      name: Authorization
security:
- bearer_auth: []
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
